Repository Fireinfern/tournament-frontend, pull requests merged in 2023-04, with the labels that each got.

#8 Feature/login register services
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/dialogs/login/login.component.html
  src/app/dialogs/login/login.component.ts
  src/app/dialogs/loginerror/loginerror.component.css
  src/app/dialogs/loginerror/loginerror.component.html
  src/app/dialogs/loginerror/loginerror.component.spec.ts
  src/app/dialogs/loginerror/loginerror.component.ts
  src/app/services/auth.service.spec.ts
  src/app/services/auth.service.ts
  src/app/services/login.service.spec.ts
  src/app/services/login.service.ts
  src/app/services/register.service.spec.ts
  src/app/services/register.service.ts
  src/app/services/tournament.service.ts
  src/app/views/register/register.component.html
  src/app/views/register/register.component.ts
Labels: enhancement

#10 Test branch
  src/app/dialogs/login/login.component.html
  src/app/dialogs/login/login.component.ts
  src/app/views/register/register.component.html
  src/app/views/register/register.component.ts
Labels: documentation, help wanted

#13 test in winner announcement in details page
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/dialogs/winner/winner.component.css
  src/app/dialogs/winner/winner.component.html
  src/app/dialogs/winner/winner.component.spec.ts
  src/app/dialogs/winner/winner.component.ts
  src/app/models/tournament.ts
  src/app/views/tournament/tournament.component.html
  src/app/views/tournament/tournament.component.ts
Labels: question
