Repository Fireinfern/tournament-frontend, pull requests merged in 2023-03, with the labels that each got.

#3 Home page and contact
  angular.json
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/footer/footer.component.css
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.spec.ts
  src/app/components/footer/footer.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/tournament-grid/tournament-grid.component.html
  src/app/services/tournament.service.ts
  src/app/views/contact/contact.component.css
  src/app/views/contact/contact.component.html
  src/app/views/contact/contact.component.spec.ts
  src/app/views/contact/contact.component.ts
  src/app/views/home/home.component.css
  src/app/views/home/home.component.html
  src/app/views/register/register.component.html
  src/assets/Images/Travellers.png
Labels: enhancement

#4 Tournament creation in menu bar
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/models/tournament.ts
  src/app/services/tournament.service.ts
  src/app/views/tournaments/tournament-create/tournament-create.component.css
  src/app/views/tournaments/tournament-create/tournament-create.component.html
  src/app/views/tournaments/tournament-create/tournament-create.component.spec.ts
  src/app/views/tournaments/tournament-create/tournament-create.component.ts
Labels: help wanted

#6 Update button
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/tournament-grid/tournament-grid.component.html
  src/app/components/tournament-grid/tournament-grid.component.ts
  src/app/dialogs/update/update-tournament.css
  src/app/dialogs/update/update-tournament.html
  src/app/dialogs/update/update-tournament.spec.ts
  src/app/dialogs/update/update-tournament.ts
  src/app/services/tournament.service.ts
Labels: documentation
